paths:
  /contacts/{contactId}:
    get:
      tags:
        - Contacts
      summary: Отримати контакт за ID
      operationId: getContactById
      description: Повертає один контакт за його унікальним ідентифікатором.
      security:
        - bearerAuth: []
      parameters:
        - name: contactId
          in: path
          required: true
          description: Ідентифікатор контакту
          schema:
            type: string
      responses:
        '200':
          description: Контакт знайдено
        '404':
          description: Контакт не знайдено

    patch:
      tags:
        - Contacts
      summary: Оновити контакт за ID
      operationId: updateContact
      description: Оновлює дані контакту.
      security:
        - bearerAuth: []
      parameters:
        - name: contactId
          in: path
          required: true
          description: Ідентифікатор контакту
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: John Doe
                email:
                  type: string
                  format: email
                  example: john.doe@example.com
                phone:
                  type: string
                  example: '+1234567890'
              additionalProperties: false
      responses:
        '200':
          description: Контакт оновлено
        '404':
          description: Контакт не знайдено

    delete:
      tags:
        - Contacts
      summary: Видалити контакт за ID
      operationId: deleteContact
      description: Видаляє контакт за ID.
      security:
        - bearerAuth: []
      parameters:
        - name: contactId
          in: path
          required: true
          description: Ідентифікатор контакту
          schema:
            type: string
      responses:
        '200':
          description: Контакт видалено
        '404':
          description: Контакт не знайдено

  /contacts:
    get:
      $ref: ../swagger/paths/contacts/get.yaml
    post:
      $ref: ../swagger/paths/contacts/post.yaml
